- screen/custom/Order/OrderDocument.xml
There are still a few columns not mapped.
> Updated document field mappings.

- screen/custom/CreateOrder/Applicant.xml
- service/mkdecision/dashboard/OrderServices.xml
issue: https://project.mkdecision.com/issues/13252
> Feat: Add validation to primary applicants fields on the Applicant screen

- service/mkdecision/dashboard/OrderServices.xml
issue: https://project.mkdecision.com/issues/13264
> fix: Add validation to property and mortgage fields

- service/mkdecision/dashboard/OrderServices.xml
issue: https://project.mkdecision.com/issues/13263
> fix: Add validation to the amount fields in the OrderHeader screen

- screen/custom/CreateOrder/Applicant.xml
- service/mkdecision/dashboard/OrderServices.xml
issue: https://project.mkdecision.com/issues/13337
> fix: Add validations to primary applicant fields in the Applicant screen

- data/ComponentMessageData.xml
- screen/custom/CreateOrder/Applicant.xml
- screen/custom/CreateOrder/OrderHeader.xml
- screen/custom/CreateOrder/Property.xml
- screen/custom/Dashboard.xml
- screen/custom/Order.xml
- screen/custom/Order/OrderApplication.xml
- screen/custom/Order/OrderDocument.xml
- screen/static/css/dashboard.css
- service/mkdecision/dashboard/OrderServices.xml
- src/main/groovy/com/mkdecision/dashboard/OrderServices.groovy
- src/main/groovy/com/mkdecision/dashboard/PartyServices.groovy
- Add property to application tab
- Add file option
- Add order statuses
- Sort order by entry date
- Show order year if entered in different year
- Bug fixes
> New features and bug fixes

- screen/custom/CreateOrder/OrderHeader.xml
- service/mkdecision/dashboard/OrderServices.xml
issue: https://project.mkdecision.com/issues/13337
> fix: Fix years and months validation

- service/mkdecision/dashboard/OrderServices.xml
- src/main/groovy/com/mkdecision/dashboard/OrderServices.groovy
issue: https://project.mkdecision.com/issues/13561
> fix: Update property fields to allow 0 to be entered

- service/mkdecision/dashboard/OrderServices.xml
issue: https://project.mkdecision.com/issues/13132#change-74006
> fix: Update middle initial validation to allow only 1 char

- screen/custom/OrderProfile.xml
issue: https://project.mkdecision.com/issues/13463
> fix: Add secure sign button to the action menu 

- service/mkdecision/dashboard/OrderServices.xml
issue: https://project.mkdecision.com/issues/13484
> fix: Add validations for optional fields

- screen/custom/OrderParty/Party.xml
- screen/custom/OrderParty/PartyEmployment.xml
- screen/custom/OrderWizard/CoApplicantEmployment.xml
- screen/custom/OrderWizard/PrimaryApplicantEmployment.xml
- service/mkdecision/dashboard/OrderServices.xml
issue: https://project.mkdecision.com/issues/13132
> fix: Add regrex validations and update order party fields to match screen outline 

- data/ComponentProductData.xml
> fix: Update fieldNames for eligibility form

- data/ComponentMessageData.xml
issue: https://project.mkdecision.com/issues/14230
> fix: Update eligibility step error message

- screen/custom/OrderParty/Party.xml
- screen/custom/OrderWizard/CoApplicant.xml
- screen/custom/OrderWizard/PrimaryApplicant.xml
- service/mkdecision/dashboard/OrderServices.xml
issue: https://project.mkdecision.com/issues/13132
> fix: Regrex QA changes

- screen/custom/OrderAgreement/CertificateOfCompletion.xml
- service/mkdecision/dashboard/AgreementServices.xml
- src/main/groovy/com/mkdecision/dashboard/AgreementServices.groovy
https://project.mkdecision.com/issues/14210
https://project.mkdecision.com/issues/14736
> fix: Saving the text agreement for dealer COC agreement

- screen/custom/OrderParty/PartyIdentity.xml
- screen/custom/OrderWizard/Agreement.xml
- screen/custom/OrderWizard/CoApplicantEmploymentPrevious.xml
- screen/custom/OrderWizard/CoApplicantIdentity.xml
- screen/custom/OrderWizard/OrderHeader.xml
- screen/custom/OrderWizard/PrimaryApplicantEmploymentPrevious.xml
- screen/custom/OrderWizard/PrimaryApplicantIdentity.xml
- template/order/OrderWidgets.xml
issue: https://project.mkdecision.com/issues/13986
> fix: Fix buttons color

- src/main/groovy/com/mkdecision/dashboard/AgreementServices.groovy
I removed some of the logic from your code and added in the close service we have that creates the entities for agreement signature and party and also injects the signature into the HTML. I went ahead and tried it out locally and it works perfectly now. I modified the customer portal also to work with this. This solves the duplicate issue and signature not showing up.
https://project.mkdecision.com/issues/14704
> fix: Use the sign agreement service to inject the signature into the textDate

- screen/custom/OrderParty/Party.xml
- screen/custom/OrderWizard/CoApplicant.xml
- screen/custom/OrderWizard/PrimaryApplicant.xml
- service/mkdecision/dashboard/OrderServices.xml
- service/mkdecision/dashboard/PartyServices.xml
- template/party/PartyForms.xml
> feat: Allow full middle name

- screen/custom/OrderWizard/Eligibility.xml
- screen/custom/OrderWizard/PrimaryApplicant.xml
Issue: https://project.mkdecision.com/issues/14253
> fix:Order saves after primary applicant is entered

- screen/custom/OrderProfile/OrderDocument.xml
issue: https://project.mkdecision.com/issues/13144
> fix: Fix typo

- screen/custom/OrderWizard/Eligibility.xml
- service/mkdecision/dashboard/OrderServices.xml
- src/main/groovy/com/mkdecision/dashboard/OrderServices.groovy
Issue: https://project.mkdecision.com/issues/15238
> add: validation for eligibility form response

- screen/custom/OrderParty/Party.xml
Issue: https://project.mkdecision.com/issues/14097
> add: Address duration header to add party form

- screen/custom/OrderProfile/OrderDocument.xml
https://project.mkdecision.com/issues/13474
> fix: Sales Rep role to view files upload by himself

- src/main/groovy/com/mkdecision/dashboard/AgreementServices.groovy
https://project.mkdecision.com/issues/15504
https://project.mkdecision.com/issues/15386
> fix: Check for agreement before creating it from agent side

- screen/custom/OrderProfile/OrderDocument.xml
> fix: Remove credit-profile from documents tab

- screen/custom/OrderProfile/OrderApplication.xml
- screen/custom/OrderProfile/OrderOverview.xml
- service/mkdecision/dashboard/PartyServices.xml
- src/main/groovy/com/mkdecision/dashboard/PartyServices.groovy
- template/party/PartyWidgets.xml
issue: https://project.mkdecision.com/issues/15446
> fix: Add middle name and suffix to overview and application tab

- screen/custom/OrderProfile.xml
issue: https://project.mkdecision.com/issues/15542
> fix: Hide cancel button if order is already cancelled

- template/party/PartyForms.xml
- template/party/PartyWidgets.xml
issue: https://project.mkdecision.com/issues/15487
> fix: Change field name and map Occupation field

- screen/custom/OrderWizard/OrderHeader.xml
- src/main/groovy/com/mkdecision/dashboard/PartyServices.groovy
Updated the get party name service
> #15513 Defaulted the sales representative to the current user

- screen/custom/OrderProfile/OrderOverview.xml
> fix: Allow user to view their own private notes

- src/main/groovy/com/mkdecision/dashboard/OrderServices.groovy
- src/main/groovy/com/mkdecision/dashboard/PartyServices.groovy
Issue: https://project.mkdecision.com/issues/15639
> fix: convert usedSince date to unix

- screen/custom/OrderProfile/OrderApplication.xml
Issue: https://project.mkdecision.com/issues/15484
> fix: Correct order of mortgage and employment list

- screen/custom/OrderProfile/OrderApplication.xml
Issue: https://project.mkdecision.com/issues/15639
> fix: Order by from date

- screen/custom/OrderProfile/OrderApplication.xml
- template/order/OrderWidgets.xml
- template/party/PartyForms.xml
- template/party/PartyWidgets.xml
Issue: https://project.mkdecision.com/issues/15483
> feat: Limit edits on open orders

- screen/custom/OrderWizard/PrimaryApplicant.xml
- service/mkdecision/dashboard/OrderServices.xml
- template/party/PartyForms.xml
issue: https://project.mkdecision.com/issues/15707
> fix: Fix fields validation

- template/party/PartyWidgets.xml
Issue: https://project.mkdecision.com/issues/15621
> fix: Address duration ui display

- template/OrderWizard/Agreement.html
issue: https://project.mkdecision.com/issues/15646
> fix: Update Agreements page texts to match button

- screen/custom/OrderProfile/OrderDocument.xml
https://project.mkdecision.com/issues/13266
> fix: Show all the agreements in the documents tab

- template/party/PartyWidgets.xml
Issue: https://project.mkdecision.com/issues/15794
> fix: Remove getFirst methods

- screen/custom/OrderProfile/OrderOverview.xml
Issue: https://project.mkdecision.com/issues/15666
> Order decision reasons

- data/ComponentMessageData.xml
- screen/custom/OrderParty/PartyEmployment.xml
- screen/custom/OrderWizard/CoApplicantEmployment.xml
- screen/custom/OrderWizard/PrimaryApplicantEmployment.xml
issue: https://project.mkdecision.com/issues/15488
> fix: Make current employment step required

- template/OrderWizard/Agreement.html
Issue: https://project.mkdecision.com/issues/15646
> fix: Update submission agreement text

- screen/custom/OrderParty/PartyEmployment.xml
- screen/custom/OrderParty/PartyEmploymentPrevious.xml
- screen/custom/OrderWizard/CoApplicantEmployment.xml
- screen/custom/OrderWizard/CoApplicantEmploymentPrevious.xml
- screen/custom/OrderWizard/Mortgage.xml
- screen/custom/OrderWizard/PrimaryApplicantEmployment.xml
- screen/custom/OrderWizard/PrimaryApplicantEmploymentPrevious.xml
Issue: https://project.mkdecision.com/issues/15484
> fix: All mort,prv emp, current emp ordered by fromDate

- screen/custom/OrderProfile/OrderOverview.xml
Issue: https://project.mkdecision.com/issues/15834?next_issue_id=15833&prev_issue_id=15839
> fix:Provide null check for decisions descriptions

- data/ComponentFinancialData.xml
- data/ComponentMessageData.xml
- screen/custom/OrderProfile/OrderApplication.xml
- screen/custom/OrderWizard/Property.xml
- service/mkdecision/dashboard/OrderServices.xml
- service/mkdecision/dashboard/PartyServices.xml
- src/main/groovy/com/mkdecision/dashboard/OrderServices.groovy
- src/main/groovy/com/mkdecision/dashboard/PartyServices.groovy
- template/party/PartyForms.xml
- template/party/PartyWidgets.xml
issue: https://project.mkdecision.com/issues/15708
> fix: Update property fields label

- screen/custom/OrderProfile/OrderOverview.xml
issue: https://project.mkdecision.com/issues/15681
> fix: Verbiage change

- screen/custom/OrderProfile/OrderDocument.xml
Issue: https://project.mkdecision.com/issues/15192
> fix: order email by sent date

- service/mkdecision/dashboard/PartyServices.xml
- template/party/PartyForms.xml
issue: https://project.mkdecision.com/issues/14440
> fix: Make Occupation and Duration fields required

- data/ComponentMessageData.xml
- template/party/PartyWidgets.xml
issue: https://project.mkdecision.com/issues/15708
> fix: Minor changes

- service/mkdecision/dashboard/OrderServices.xml
- template/party/PartyForms.xml
Issue: https://project.mkdecision.com/issues/15448
> fix: Fix residential address to not allow PO Box and update edit party validations

- screen/custom/OrderProfile/OrderApplication.xml
Issue: https://project.mkdecision.com/issues/15484
> fix: Order employment entry by partyRelationshipId

- data/ComponentRoleData.xml
https://project.mkdecision.com/issues/15255
> feat: Add new seed data for roles' editablility

- screen/custom/OrderProfile/OrderDocument.xml
Issue: https://project.mkdecision.com/issues/15192
> fix: Agreements ordered by dates

- template/party/PartyForms.xml
- template/party/PartyWidgets.xml
issue: https://project.mkdecision.com/issues/15510
> fix: Add Self-Employment and Add Independent Contractor buttons

- screen/custom/OrderParty/Party.xml
- screen/custom/OrderWizard/CoApplicant.xml
- screen/custom/OrderWizard/PrimaryApplicant.xml
- service/mkdecision/dashboard/OrderServices.xml
- service/mkdecision/dashboard/PartyServices.xml
- src/main/groovy/com/mkdecision/dashboard/OrderServices.groovy
- src/main/groovy/com/mkdecision/dashboard/PartyServices.groovy
- template/party/PartyForms.xml
issue: https://project.mkdecision.com/issues/15449
> fix: Make email address fields on new order in Dealer Dashboard optional

- screen/custom/OrderProfile/DecisionReasons.xml
- screen/custom/OrderProfile/OrderOverview.xml
Issue: https://project.mkdecision.com/issues/15666
> fix: Return multiple pending declines with dynamic reasons listed

- screen/custom/OrderProfile.xml
https://project.mkdecision.com/issues/15386
> feat: Check for COC agreement that is active for conditional response

- src/main/groovy/com/mkdecision/dashboard/PartyServices.groovy
- template/party/PartyForms.xml
issue: https://project.mkdecision.com/issues/15510
> fix: Replace EmpsContractor with the new EmpsIndependentContractor enum

- screen/custom/OrderProfile/OrderAgreement.xml
- screen/custom/OrderProfile/OrderDocument.xml
https://project.mkdecision.com/issues/13975
https://project.mkdecision.com/issues/13266
> feat: Fix the agreement download and view for documents tab

- screen/custom/OrderWizard/OrderHeader.xml
- screen/custom/OrderWizard/PrimaryApplicant.xml
- template/party/PartyWidgets.xml
Issue: https://project.mkdecision.com/issues/15906
> fix: find saved order header fields on

- screen/custom/OrderProfile/OrderDocument.xml
https://project.mkdecision.com/issues/13975
> feat: change the hyperlink location

- screen/custom/OrderProfile/OrderOverview.xml
issue: https://project.mkdecision.com/issues/15850
> fix: Display decisions in Decision section

- screen/custom/OrderParty/Party.xml
- screen/custom/OrderWizard/CoApplicant.xml
- screen/custom/OrderWizard/PrimaryApplicant.xml
- service/mkdecision/dashboard/OrderServices.xml
- service/mkdecision/dashboard/PartyServices.xml
- src/main/groovy/com/mkdecision/dashboard/OrderServices.groovy
- src/main/groovy/com/mkdecision/dashboard/PartyServices.groovy
- template/party/PartyForms.xml
- template/party/PartyWidgets.xml
issue: https://project.mkdecision.com/issues/16231
> fix: Remove Employment Status field on personal info screen

- screen/custom/OrderProfile/OrderOverview.xml
Issue: https://project.mkdecision.com/issues/15792
> feat: show custom requirement if there is one

- screen/custom/OrderProfile.xml
Issue: https://project.mkdecision.com/issues/15541
> fix: Show correct accept button when order status is proposed

- screen/custom/OrderProfile.xml
Issue: https://project.mkdecision.com/issues/17273
> fix: status after proposed for each product

- template/party/PartyWidgets.xml
issue: https://project.mkdecision.com/issues/16920
> fix: Show Edit button for employment section

- screen/custom/OrderParty/Party.xml
- screen/custom/OrderProfile/OrderOverview.xml
- screen/custom/OrderWizard/CoApplicant.xml
- template/party/PartyWidgets.xml
issue: https://project.mkdecision.com/issues/17019
> fix: Add button to delete party 

- screen/custom/OrderWizard/Property.xml
- template/party/PartyForms.xml
- template/party/PartyWidgets.xml
issue: https://project.mkdecision.com/issues/17256
> fix: Update property screen

- screen/custom/OrderWizard/CoApplicant.xml
issue: https://project.mkdecision.com/issues/17019
> fix: Remove back button once party has been added

- screen/custom/OrderParty/Party.xml
- screen/custom/OrderWizard/CoApplicant.xml
issue: https://project.mkdecision.com/issues/17019
> fix: Update button and confirmation text

- src/main/groovy/com/mkdecision/dashboard/OrderServices.groovy
- src/main/groovy/com/mkdecision/dashboard/PartyServices.groovy
Issue: https://project.mkdecision.com/issues/17353
> Update resident enum

- .gitignore
- screen/custom/OrderProfile/OrderDocument.xml
https://project.mkdecision.com/issues/17100
> feat: Add xsl-fo flow to show agreements in pdf version

- data/ComponentOrderData.xml
- screen/custom/Orders.xml
issue: https://project.mkdecision.com/issues/17440
> fix: Move Evergreen-specific code to configuration

- screen/custom/OrderWizard/Agreement.xml
- screen/custom/OrderWizard/CoApplicant.xml
- screen/custom/OrderWizard/CoApplicantMaritalStatus.xml
- screen/custom/OrderWizard/Mortgage.xml
- screen/custom/OrderWizard/PrimaryApplicant.xml
- screen/custom/OrderWizard/PrimaryApplicantMaritalStatus.xml
- service/mkdecision/dashboard/OrderServices.xml
- src/main/groovy/com/mkdecision/dashboard/OrderServices.groovy
- src/main/groovy/com/mkdecision/dashboard/PartyServices.groovy
- template/party/PartyWidgets.xml
https://project.mkdecision.com/issues/15482
>  feat: move material status to later in flow

- data/ComponentMessageData.xml
- service/mkdecision/dashboard/PartyServices.xml
- src/main/groovy/com/mkdecision/dashboard/PartyServices.groovy
- template/party/PartyForms.xml
- template/party/PartyWidgets.xml
issue: https://project.mkdecision.com/issues/15405
> Fix: Update mortgage screen

- screen/custom/OrderProfile.xml
issue: https://project.mkdecision.com/issues/17869
> fix: Add confirmation text when user click on cancel button 

- src/main/groovy/com/mkdecision/dashboard/OrderServices.groovy
- template/party/PartyWidgets.xml
https://project.mkdecision.com/issues/15482
> feat: Update marital status dropdown options and always show for joint applications

- screen/custom/OrderWizard/Mortgage.xml
- service/mkdecision/dashboard/PartyServices.xml
- src/main/groovy/com/mkdecision/dashboard/PartyServices.groovy
- template/party/PartyForms.xml
- template/party/PartyWidgets.xml
https://project.mkdecision.com/issues/17932
https://project.mkdecision.com/issues/17868
https://project.mkdecision.com/issues/17854
> fix: Mortgage screen creating & update

- template/party/PartyWidgets.xml
https://project.mkdecision.com/issues/15482
> fix: Update field name to be user friendly

- screen/custom/OrderWizard/Property.xml
- template/party/PartyForms.xml
issue: https://project.mkdecision.com/issues/17902
> fix: Remove text from property section

- screen/static/css/mk-overrides.css
Issue: https://project.mkdecision.com/issues/13787
> feat: invert evergreen logo

- src/main/groovy/com/mkdecision/dashboard/OrderServices.groovy
issue: https://project.mkdecision.com/issues/17583
> fix: Email validation error

- screen/static/css/mk-overrides.css
Issue: https://project.mkdecision.com/issues/13787
> fix: Change evergreen logo to original logo

- template/party/PartyForms.xml
- template/party/PartyWidgets.xml
Issue: https://project.mkdecision.com/issues/18083
> fix: store geo Id to properly display state on lender dashboard

- screen/custom/OrderWizard/OrderHeader.xml
issue: https://project.mkdecision.com/issues/18342
> fix: Add EHL-FDIC Logo

- screen/custom/OrderWizard/CoApplicant.xml
issue: https://project.mkdecision.com/issues/14440
> fix: Added validations for co-app fields

- data/ComponentOrderData.xml
- screen/custom/OrderProfile/OrderDocument.xml
issue: https://project.mkdecision.com/issues/18509
> fix: Hide financial summary from Finance Manager and Sales Rep

- screen/custom/OrderProfile.xml
Issue: https://project.mkdecision.com/issues/18551
> fix: Can cancel order on set permission and/or order open status

- template/party/PartyForms.xml
https://project.mkdecision.com/issues/18425
> fix: Use the correct martial status dropdown choices

- template/party/PartyForms.xml
- template/party/PartyWidgets.xml
https://project.mkdecision.com/issues/19540
> fix: Fix id options dropdown not displaying

- service/mkdecision/dashboard/PartyServices.xml
- template/party/PartyForms.xml
- template/party/PartyWidgets.xml
https://project.mkdecision.com/issues/19288
> fix: Only require marital status when requirements are met

- screen/custom/OrderWizard/Mortgage.xml
- service/mkdecision/dashboard/PartyServices.xml
- src/main/groovy/com/mkdecision/dashboard/PartyServices.groovy
- template/party/PartyWidgets.xml
Issue: https://project.mkdecision.com/issues/19732
> feat: Create a mock mortgage to satisfy validation

- src/main/groovy/com/mkdecision/dashboard/PartyServices.groovy
https://project.mkdecision.com/issues/19993
> fix: Make email field optional when editing party

- src/main/groovy/com/mkdecision/dashboard/PartyServices.groovy
https://project.mkdecision.com/issues/19745
> fix: Added validation for ID issue date to not allow issue date before birthdate

- src/main/groovy/com/mkdecision/dashboard/PartyServices.groovy
https://project.mkdecision.com/issues/19950
https://project.mkdecision.com/issues/19946
> fix: Calculate previous employment fromDate and toDate based on current emp fromDate

- screen/custom/OrderProfile/OrderApplication.xml
- screen/custom/OrderWizard/CoApplicant.xml
- screen/custom/OrderWizard/PrimaryApplicant.xml
- service/mkdecision/dashboard/OrderServices.xml
- src/main/groovy/com/mkdecision/dashboard/OrderServices.groovy
https://project.mkdecision.com/issues/20098
> fix: Added sequenceNum to orderPartParty
